'use server';

/**
 * @fileOverview Generates campaign strategies using AI based on provided data and objectives.
 *
 * - generateCampaignStrategy - A function that generates a campaign strategy.
 * - GenerateCampaignStrategyInput - The input type for the generateCampaignStrategy function.
 * - GenerateCampaignStrategyOutput - The return type for the generateCampaignStrategy function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const GenerateCampaignStrategyInputSchema = z.object({
  campaignData:
    z.string().describe('Data about the campaign, including past performance, voter demographics, and key issues.'),
  objectives: z.string().describe('The objectives of the campaign, such as increasing voter turnout or winning a specific demographic.'),
  resourceConstraints:
    z.string().optional().describe('Any limitations on resources, such as budget or staff.'),
});
export type GenerateCampaignStrategyInput = z.infer<typeof GenerateCampaignStrategyInputSchema>;

const GenerateCampaignStrategyOutputSchema = z.object({
  strategy: z.string().describe('A comprehensive campaign strategy generated by AI.'),
  keyRecommendations:
    z.string().describe('Key recommendations for implementing the campaign strategy.'),
  potentialRisks: z.string().describe('Potential risks and challenges associated with the strategy.'),
});
export type GenerateCampaignStrategyOutput = z.infer<typeof GenerateCampaignStrategyOutputSchema>;

export async function generateCampaignStrategy(
  input: GenerateCampaignStrategyInput
): Promise<GenerateCampaignStrategyOutput> {
  return generateCampaignStrategyFlow(input);
}

const generateCampaignStrategyPrompt = ai.definePrompt({
  name: 'generateCampaignStrategyPrompt',
  input: {schema: GenerateCampaignStrategyInputSchema},
  output: {schema: GenerateCampaignStrategyOutputSchema},
  prompt: `You are an AI-powered campaign strategist. Your task is to generate a comprehensive campaign strategy based on the provided campaign data, objectives, and resource constraints.

Campaign Data: {{{campaignData}}}
Objectives: {{{objectives}}}
Resource Constraints: {{{resourceConstraints}}}

Generate a detailed campaign strategy, including key recommendations and potential risks.

Ensure the strategy is actionable and aligned with the objectives, taking into account any resource limitations.

Follow the output schema and use the descriptions to ensure output is formatted properly.

Strategy:`,
});

const generateCampaignStrategyFlow = ai.defineFlow(
  {
    name: 'generateCampaignStrategyFlow',
    inputSchema: GenerateCampaignStrategyInputSchema,
    outputSchema: GenerateCampaignStrategyOutputSchema,
  },
  async input => {
    const {output} = await generateCampaignStrategyPrompt(input);
    return output!;
  }
);
